---
- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: Clone elastalert repository
  git:
    repo: "{{ elastalert_git_repo }}"
    accept_hostkey: yes
    dest: /opt/elastalert
    version: "{{ elastalert_version }}"

- name: Install virtualenv
  pip:
    name: virtualenv

- name: Install supervisor
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - supervisor

- name: add supervisor to boot
  service: name=supervisor enabled=yes

- name: Avoid errors that result from InsecurePlatformWarning
  apt:
    name: "{{ item }}"
  with_items:
    - python-dev
    - libffi-dev
    - libssl-dev
  tags:
    - apt

- name: Install elastalert dependencies
  pip:
    requirements: /opt/elastalert/requirements.txt
    virtualenv: /opt/elastalert/venv

- name: Install elastalert
  command: /opt/elastalert/venv/bin/python setup.py install
  args:
    chdir: /opt/elastalert

- name: Flush handlers to ensure a local elasticsearch has been started
  meta: flush_handlers

- name: Install httplib2
  pip:
    name: httplib2

- name: Check existence of elastalert metadata index
  uri:
    url: "http://{{ elastalert_elasticsearch_host }}:{{ elastalert_elasticsearch_port }}/{{ elastalert_index }}"
    method: HEAD
    status_code:
      - 200
      - 404
  register: elastalert_index_check

- name: Create elasticsearch index for elastalert metadata
  command: /opt/elastalert/venv/bin/elastalert-create-index --host "{{ elastalert_elasticsearch_host }}" --port "{{ elastalert_elasticsearch_port }}" --no-auth --no-ssl --url-prefix "" --index "{{ elastalert_index }}" --old-index ""
  args:
    chdir: /opt/elastalert
  when: elastalert_index_check.status == 404
  notify:
    - restart elastalert

- name: Add elastalert group
  group:
    name: elastalert
    state: present

- name: Add elastalert user
  user:
    name: elastalert
    group: elastalert
    system: yes
    state: present

- name: Create rules directory
  file:
    path: /etc/elastalert/rules
    state: directory
    owner: root
    group: root
    mode: 0755
  notify:
    - restart elastalert

- name: Process config template
  template:
    src: config.yaml
    dest: /etc/elastalert/config.yaml

- name: Supervisor config to run elastalert
  template: src=supervisor.conf.j2 dest=/etc/supervisor/conf.d/elastalert.conf
  notify: restart supervisor
